@startuml
/'
集約A <|-- 集約B
汎化A --o 汎化B
関係A -- 関係B
'/
コーヒー豆 --o 生豆
コーヒー豆 --o ローストされた豆
コーヒー豆 <|-- 産地
コーヒー豆 <|-- 生産者
コーヒー豆 <|-- 品種
' 焙煎
コーヒー豆 <|-- 焙煎
焙煎 <|-- 焙煎日
焙煎 <|-- 焙煎機
焙煎 <|-- 焙煎度
焙煎 <|-- 焙煎家
' グラインド
コーヒー豆 <|-- グラインド
グラインド <|-- グラインダー
グラインド <|-- グラインド日
' 淹れる
コーヒー豆 <|-- 淹れる
淹れる <|-- コーヒーメーカー
コーヒーメーカー --o ペーパーフィルター
コーヒーメーカー --o v60
コーヒーメーカー --o サイフォン	
コーヒーメーカー --o ネル	
@enduml