@startuml

title 豆の一覧を表示する
' ロバストネス図にするために、ユースケースとして表示しておく
(豆の一覧を表示する)

' アクター一覧
actor ユーザー

/'
  名詞
  バウンダリー一覧
  エンティティ一覧
'/
boundary 豆一覧ページ
boundary エラーダイアログ

entity 豆のリスト
entity 最初の豆登録の案内

/'
  動詞
  コントロール一覧
'/
control 飲み終わっていない豆の検索
control 検索結果が1件以上か
control エラーの表示

' 基本コース
ユーザー --> 豆一覧ページ
豆一覧ページ --> 飲み終わっていない豆の検索
飲み終わっていない豆の検索 --> 検索結果が1件以上か
検索結果が1件以上か --> 豆のリスト : はい

' 代替コース1
検索結果が1件以上か --> 最初の豆登録の案内 : いいえ

' 代替コース2
飲み終わっていない豆の検索 --> エラーの表示
エラーの表示 --> エラーダイアログ

@enduml